# As long as the MXE ticket at https://github.com/mxe/mxe/pull/1447 is
# not resolved, we need to build CEGUI for Windows ourselves. On all
# other platforms, we rely on the user to provide it.
if (Win32)
  message("-- Building CEGUI ourselves for Win32")

  ExternalProject_Add(CEGUI
    SOURCE_DIR "${TSC_SOURCE_DIR}/../cegui-0.8.7"
    CMAKE_ARGS -DCEGUI_BUILD_IMAGECODEC_DEVIL=ON -DCEGUI_BUILD_RENDERER_OPENGL=ON -DCEGUI_BUILD_XMLPARSER_LIBXML2=ON
    INSTALL_COMMAND "")

  set(CEGUI_LIBRARIES "CEGUICoreWindowRendererSet CEGUIDevILImageCodec CEGUILibXMLParser CEGUIOpenGLRenderer-0 CEGUIBase-0")
  set(CEGUI_INCLUDE_DIR "${TSC_SORUCE_DIR}/../cegui-0.8.7/cegui/include")

  ## CEGUI build configuration
  #set(CEGUI_BUILD_IMAGECODEC_CORONA OFF)
  #set(CEGUI_BUILD_IMAGECODEC_DEVIL ON)
  #set(CEGUI_BUILD_IMAGECODEC_FREEIMAGE OFF)
  #set(CEGUI_BUILD_IMAGECODEC_PVR OFF)
  #set(CEGUI_BUILD_IMAGECODEC_SDL2 OFF)
  #set(CEGUI_BUILD_IMAGECODEC_SILLY OFF)
  #set(CEGUI_BUILD_IMAGECODEC_STB OFF)
  #set(CEGUI_BUILD_IMAGECODEC_TGA OFF)
  #
  #set(CEGUI_BUILD_RENDERER_DIRECT3D10 OFF)
  #set(CEGUI_BUILD_RENDERER_DIRECT3D11 OFF)
  #set(CEGUI_BUILD_RENDERER_DIRECT3D9 OFF)
  #set(CEGUI_BUILD_RENDERER_DIRECTFB OFF)
  #set(CEGUI_BUILD_RENDERER_IRRLICHT OFF)
  #set(CEGUI_BUILD_RENDERER_NULL OFF)
  #set(CEGUI_BUILD_RENDERER_OGRE OFF)
  #set(CEGUI_BUILD_RENDERER_OPENGL ON)
  #set(CEGUI_BUILD_RENDERER_OPENGL3 OFF)
  #set(CEGUI_BUILD_RENDERER_OPENGLES OFF)
  #
  #set(CEGUI_BUILD_XMLPARSER_EXPAT OFF)
  #set(CEGUI_BUILD_XMLPARSER_LIBXML2 ON)
  #set(CEGUI_BUILD_XMLPARSER_RAPIDXML OFF)
  #set(CEGUI_BUILD_XMLPARSER_TINYXML OFF)
  #set(CEGUI_BUILD_XMLPARSER_XERCES OFF)
  #
  #set(CEGUI_BUILD_LUA_MODULE OFF)
  #set(CEGUI_BUILD_PYTHON_MODULES OFF)
  #
  #set(CEGUI_SAMPLES_ENABLED OFF)
  #set(CEGUI_BUILD_TESTS OFF)
  #
  ## Now add it to our build
  #add_subdirectory("${TSC_SOURCE_DIR}/../cegui-0.8.7")
else()
  find_package(CEGUI COMPONENTS OpenGL REQUIRED)
endif()